# Generated by Django 4.2.26 on 2025-11-07 15:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('badge_text', models.CharField(blank=True, max_length=100, verbose_name='Текст бейджа')),
                ('badge_color', models.CharField(choices=[('gold', 'Золотой'), ('pink', 'Розовый'), ('blue', 'Синий')], default='gold', max_length=20, verbose_name='Цвет бейджа')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Достижение / Факт',
                'verbose_name_plural': 'Достижения и факты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес приёма')),
                ('telegram_link', models.CharField(blank=True, max_length=150, verbose_name='Ссылка на Telegram')),
                ('whatsapp_link', models.CharField(blank=True, max_length=150, verbose_name='Ссылка на WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email для заявок')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название направления')),
                ('description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Направление помощи',
                'verbose_name_plural': 'Направления помощи',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EducationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Этап образования',
                'verbose_name_plural': 'Образование',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=300, verbose_name='Подзаголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='heroes/', verbose_name='Фото врача (700×700)')),
                ('cta_text', models.CharField(default='Записаться на приём', max_length=50, verbose_name='Текст кнопки записи')),
            ],
            options={
                'verbose_name': 'Главная секция',
                'verbose_name_plural': 'Главная секция',
            },
        ),
        migrations.CreateModel(
            name='SEOAndContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(default='Доктор Гвоздев А.Н. | Урогинеколог в Москве', max_length=100, verbose_name='Title для SEO')),
                ('meta_description', models.CharField(default='Врач-урогинеколог высшей категории. Операции при недержании, пролапсе, свищах. Автор патентованной методики.', max_length=200, verbose_name='Description для SEO')),
                ('og_image', models.ImageField(blank=True, help_text='Рекомендуется 1200×630 px', null=True, upload_to='seo/', verbose_name='OG-изображение (для соцсетей)')),
            ],
            options={
                'verbose_name': 'SEO и контент',
                'verbose_name_plural': 'SEO и контент',
            },
        ),
        migrations.CreateModel(
            name='WorkExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название кейса (для админа)')),
                ('public_title', models.CharField(default='Операция', max_length=200, verbose_name='Заголовок на сайте')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание (на сайте, до раскрытия)')),
                ('image_original', models.ImageField(help_text='Фото будет размыто на сайте до клика', upload_to='work_examples/', verbose_name='Фото (оригинал)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Пример работы',
                'verbose_name_plural': 'Примеры работ',
                'ordering': ['order'],
            },
        ),
    ]
