# Generated by Django 4.2.26 on 2025-11-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoandcontent',
            name='meta_title',
            field=models.CharField(default='Доктор Гвоздев М.Ю. | Урогинеколог в Москве', max_length=100, verbose_name='Title для SEO'),
        ),
    ]
