# Generated by Django 4.2.26 on 2025-11-10 07:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_seoandcontent_meta_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', ckeditor.fields.RichTextField(verbose_name='Биография')),
                ('experience_years', models.PositiveIntegerField(default=18, verbose_name='Стаж (лет)')),
                ('patents', ckeditor.fields.RichTextField(blank=True, verbose_name='Патенты и разработки')),
                ('awards', ckeditor.fields.RichTextField(blank=True, verbose_name='Награды и заслуги')),
            ],
            options={
                'verbose_name': 'О враче',
                'verbose_name_plural': 'О враче',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Контент')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Дневник врача',
                'verbose_name_plural': 'Дневник врача',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название события')),
                ('date', models.DateField(verbose_name='Дата')),
                ('location', models.CharField(max_length=200, verbose_name='Место')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('link', models.URLField(blank=True, help_text='Ссылка на мероприятие', verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название операции')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (например, fa-syringe)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Отзыв')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UsefulInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyses', ckeditor.fields.RichTextField(verbose_name='Необходимые анализы')),
                ('hospital_guide', ckeditor.fields.RichTextField(verbose_name='Памятка для пациенток')),
            ],
            options={
                'verbose_name': 'Полезная информация',
                'verbose_name_plural': 'Полезная информация',
            },
        ),
    ]
