# Generated by Django 4.2.26 on 2025-11-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutdoctor_blogpost_event_procedure_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Фото'),
        ),
    ]
