# Generated by Django 4.2.26 on 2026-01-09 12:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_procedure_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название клиники')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('map_link', models.URLField(blank=True, verbose_name='Ссылка на карту (Google Maps и т.п.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Адрес клиники',
                'verbose_name_plural': 'Адреса клиник',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='usefulinfo',
            options={'verbose_name': 'Важное пациенткам', 'verbose_name_plural': 'Важное пациенткам'},
        ),
        migrations.RemoveField(
            model_name='usefulinfo',
            name='analyses',
        ),
        migrations.RemoveField(
            model_name='usefulinfo',
            name='hospital_guide',
        ),
        migrations.AddField(
            model_name='hero',
            name='video_url',
            field=models.URLField(blank=True, help_text='Можно загрузить в облако и вставить прямую ссылку на .mp4 файл', verbose_name='Ссылка на видео (прямая, например, .mp4)'),
        ),
        migrations.AddField(
            model_name='usefulinfo',
            name='anesthesia_info',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Обезболивание при операции'),
        ),
        migrations.AddField(
            model_name='usefulinfo',
            name='postop_period',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Послеоперационный период'),
        ),
        migrations.AddField(
            model_name='usefulinfo',
            name='prep_consultation',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Подготовка к консультации'),
        ),
        migrations.AddField(
            model_name='usefulinfo',
            name='prep_surgery',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Подготовка к операции'),
        ),
    ]
