# Generated by Django 4.2.26 on 2026-01-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cliniclocation_alter_usefulinfo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='video_url',
        ),
        migrations.AddField(
            model_name='hero',
            name='video_file',
            field=models.FileField(blank=True, help_text='Поддерживаемый формат: .mp4. Рекомендуется сжать видео до 30–50 МБ.', upload_to='hero_videos/', verbose_name='Видео (MP4, до 50 МБ)'),
        ),
    ]
