# Generated by Django 4.2.26 on 2026-03-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_hero_video_url_hero_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniclocation',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт клиники'),
        ),
    ]
