# Generated by Django 4.2.26 on 2026-03-25 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_testimonial_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='related_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event', verbose_name='Связанное мероприятие'),
        ),
    ]
