# Generated by Django 4.2.30 on 2026-09-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_blogpost_related_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон / Telegram')),
                ('message', models.TextField(verbose_name='Что беспокоит')),
                ('consent_given', models.BooleanField(default=False, help_text='Чекбокс на форме подтверждён пользователем', verbose_name='Согласие на обработку ПД')),
                ('consent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата согласия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP отправителя')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent браузера')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('admin_note', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заявка (запись на приём)',
                'verbose_name_plural': 'Заявки (записи на приём)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='procedure',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='procedures/', verbose_name='Фото'),
        ),
    ]
