# Generated by Django 4.2.30 on 2026-06-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_blogpost_related_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=120, verbose_name='Телефон / Telegram')),
                ('message', models.TextField(blank=True, max_length=2000, verbose_name='Сообщение')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Получена')),
            ],
            options={
                'verbose_name': 'Заявка на приём',
                'verbose_name_plural': 'Заявки на приём',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='procedure',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='procedures/', verbose_name='Фото'),
        ),
    ]
