# Generated by Django 4.2.30 on 2026-09-16 06:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_lead_alter_procedure_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(default='Здравствуйте,', max_length=200, verbose_name='Приветствие')),
                ('intro', models.CharField(default='Меня зовут Михаил Юрьевич, врач-урогинеколог.', max_length=200, verbose_name='Кто я')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст обращения')),
                ('signature', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctor/', verbose_name='Фото врача')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Обращение врача',
                'verbose_name_plural': 'Обращение врача',
            },
        ),
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Например: 30+ или 20 000+', max_length=20, verbose_name='Число')),
                ('label', models.CharField(help_text='Например: лет хирургического опыта', max_length=80, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Цифра под баннером',
                'verbose_name_plural': 'Цифры под баннером',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='cliniclocation',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='cliniclocation',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Например: администратор Ирина', max_length=200, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='cliniclocation',
            name='metro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Метро / как добраться'),
        ),
        migrations.AddField(
            model_name='cliniclocation',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон для записи'),
        ),
        migrations.AddField(
            model_name='cliniclocation',
            name='phone_extra',
            field=models.CharField(blank=True, max_length=100, verbose_name='Дополнительный телефон'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='max_link',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ссылка на MAX'),
        ),
        migrations.AddField(
            model_name='event',
            name='video_file',
            field=models.FileField(blank=True, help_text='Короткий анонс или запись. Формат .mp4', upload_to='events/video/', verbose_name='Видео (MP4)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(blank=True, help_text='Самые яркие слова из отзыва. Если пусто — возьмём начало текста.', max_length=250, verbose_name='Заголовок отзыва'),
        ),
        migrations.AlterField(
            model_name='cliniclocation',
            name='map_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на карту (Яндекс.Карты и т.п.)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение (анонс)'),
        ),
    ]
