# Generated by Django 4.2.30 on 2026-09-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_doctorletter_herostat_cliniclocation_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorletter',
            name='banner',
            field=models.ImageField(blank=True, help_text='Горизонтальное фото, например из операционной', null=True, upload_to='doctor/', verbose_name='Широкое фото под обращением'),
        ),
    ]
