# Generated by Django 4.2.30 on 2026-09-16 06:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_doctorletter_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('nav_title', models.CharField(max_length=80, verbose_name='Название в меню')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок на баннере')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Подзаголовок на баннере')),
                ('counter', models.CharField(blank=True, help_text='Например: более 6 500 операций', max_length=120, verbose_name='Счётчик на баннере')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='diseases/', verbose_name='Фото баннера')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (например, fa-syringe)')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание для карточки')),
                ('video_file', models.FileField(blank=True, help_text='Файл проигрывается прямо на странице', null=True, upload_to='diseases/video/', verbose_name='Видео (MP4)')),
                ('video_url', models.URLField(blank=True, help_text='Если файла нет — ссылка на VK Видео / Rutube / YouTube', verbose_name='Ссылка на видео')),
                ('video_poster', models.ImageField(blank=True, null=True, upload_to='diseases/', verbose_name='Обложка видео')),
                ('lead', ckeditor.fields.RichTextField(blank=True, verbose_name='Вступление')),
                ('highlight_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок врезки')),
                ('highlight_text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст врезки')),
                ('advantages', ckeditor.fields.RichTextField(blank=True, verbose_name='Преимущества (списком)')),
                ('benefits', ckeditor.fields.RichTextField(blank=True, verbose_name='Плюсы операции (списком)')),
                ('appeal', ckeditor.fields.RichTextField(blank=True, verbose_name='Обращение к пациенткам')),
                ('details', ckeditor.fields.RichTextField(blank=True, verbose_name='Подробнее об операции')),
                ('about', ckeditor.fields.RichTextField(blank=True, verbose_name='Подробнее о заболевании')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Страница заболевания',
                'verbose_name_plural': 'Страницы заболеваний',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('video', 'Видео'), ('image', 'Фото / анонс')], default='image', max_length=10, verbose_name='Тип слайда')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подпись')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Фото (оно же обложка видео)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='slides/video/', verbose_name='Видео (MP4)')),
                ('button_text', models.CharField(blank=True, max_length=60, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, max_length=250, verbose_name='Ссылка кнопки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Слайд баннера',
                'verbose_name_plural': 'Слайды баннера',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Например: 01', max_length=4, verbose_name='Номер')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Подзаголовок')),
                ('body', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст памятки')),
                ('file', models.FileField(blank=True, help_text='Если загружен — на странице появится кнопка «Скачать»', null=True, upload_to='memos/', verbose_name='Файл для скачивания (PDF/DOCX)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Памятка пациентке',
                'verbose_name_plural': 'Памятки пациенткам',
                'ordering': ['order', 'number'],
            },
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='max_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr/', verbose_name='QR-код MAX'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='telegram_qr',
            field=models.ImageField(blank=True, help_text='Картинка QR для быстрого перехода в канал', null=True, upload_to='qr/', verbose_name='QR-код Telegram'),
        ),
        migrations.AddField(
            model_name='lead',
            name='attachment',
            field=models.FileField(blank=True, help_text='Выписки, результаты обследований', null=True, upload_to='leads/%Y/%m/', verbose_name='Вложение от пациентки'),
        ),
        migrations.AddField(
            model_name='lead',
            name='mail_sent',
            field=models.BooleanField(default=False, verbose_name='Письмо врачу отправлено'),
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
                ('disease', models.ForeignKey(blank=True, help_text='Если пусто — вопрос общий', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='core.disease', verbose_name='Относится к заболеванию')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопросы и ответы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='memo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diseases', to='core.memo', verbose_name='Памятка пациентке'),
        ),
    ]
