# Generated by Django 4.2.30 on 2026-09-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_disease_heroslide_memo_contactinfo_max_qr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Подпись')),
                ('cover', models.ImageField(upload_to='publications/', verbose_name='Обложка')),
                ('file', models.FileField(blank=True, help_text='Если файла нет — можно указать ссылку', null=True, upload_to='publications/', verbose_name='Файл (PDF)')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Это может быть полезно',
                'ordering': ['order', 'id'],
            },
        ),
    ]
