# Generated by Django 4.2.30 on 2026-09-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='video_caption',
            field=models.CharField(blank=True, help_text='Например: демонстрационный ролик', max_length=200, verbose_name='Подпись под видео'),
        ),
    ]
