# Generated by Django 4.2.30 on 2026-09-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_disease_video_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdoctor',
            name='video_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подпись под видео'),
        ),
        migrations.AddField(
            model_name='aboutdoctor',
            name='video_file',
            field=models.FileField(blank=True, help_text='Показывается в блоке «Обо мне» рядом с биографией', null=True, upload_to='doctor/video/', verbose_name='Видео о враче (MP4)'),
        ),
        migrations.AddField(
            model_name='aboutdoctor',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='doctor/', verbose_name='Обложка видео'),
        ),
        migrations.AddField(
            model_name='aboutdoctor',
            name='video_url',
            field=models.URLField(blank=True, help_text='Если файла нет', verbose_name='Ссылка на видео'),
        ),
    ]
